{% set name = "photochem_clima_data" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem_clima_data/archive/v{{ version }}.tar.gz
  sha256: c26917301b380ab17c040b612627afc4703eda6e13291cd9141d6b74d0720950

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - pyyaml
 
test:
  imports:
    - photochem_clima_data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Nicholaswogan/photochem_clima_data
  summary: Data for Photochem and Clima packages
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholaswogan
