{% set name = "photochem_clima_data" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Nicholaswogan/photochem_clima_data/archive/v{{ version }}.tar.gz
  sha256: c3ee9de853c3d2960def9415bc178942315b5df8f05aa486fabafedf59f83527

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.2
    - pip
  run:
    - python >=3.7
    - h5py
    - pyyaml

test:
  imports:
    - photochem_clima_data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nicholaswogan/photochem_clima_data
  summary: Data for Photochem and Clima packages
  license: GPL-2.0-or-later
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholaswogan
